// Generated by ts-to-zod
import { z } from "zod";
export const APIGatewayProxyEventHeadersSchema = z.record(
    z.string().nullable()
);

export const APIGatewayInputSchema = z.object({
    // TODO: Type this for later
    body: z.object({}).nullable(),
    header: APIGatewayProxyEventHeadersSchema,
    path: z.object({}),
    querystring: z.object({}).nullable(),
});


export type APIGatewayInputType = z.infer<typeof APIGatewayInputSchema>;


export interface StepFunctionsCall<T>{
    Payload: T,
    ExecutedVersion: "$LATEST"
}